### ISSUE TITLE
URL转义你没有做

### ISSUE THREAD

**Issue by coyool** [xyhuangjinfu/MiniDownloader#12]
比如 /&^%$#@这些特殊符号一定死掉

**Comment by xyhuangjinfu** [comment]
你好，感谢反馈。
可以给出一个具体的url示例吗？因为这边我简单的试了一下，在路径中加入特殊字符，貌似没有出现问题。
http://192.168.1.2/te&st.txt

**Comment by coyool** [comment]
FTP的时候的用户名和密码包含在路径里面, 就挂掉了

**Comment by xyhuangjinfu** [comment]
感谢反馈，字符转义问题已解决，版本号 0.0.3。
