### ISSUE TITLE
FTP的服务器类型没有判断

### ISSUE THREAD

**Issue by coyool** [xyhuangjinfu/MiniDownloader#13]
windows ftp 服务器 需要使用\r\n 
linux类的是 \n

**Comment by xyhuangjinfu** [comment]
你好，感谢反馈。
你的意思是说，在命令后面的结束符，windows和linux不一样，是吗？因为我在windows平台和Android平台上测试过，目前没发现问题。不知道你那边是不是碰到了什么问题？

**Comment by coyool** [comment]
只支持被动模式好像不好, 能不能用其他FTP库封装一下
客户用的FTP好像没有开被动模式, 
不知道他用什么搭的ftp, 只知道操作系统是2008的

**Comment by xyhuangjinfu** [comment]
感谢反馈，已经添加ftp主动模式支持，版本0.0.4 。 当服务器不支持被动模式时，内部会自动尝试转换为主动模式。
