### ISSUE TITLE
rsp code 150  is a valid rsp code

### ISSUE THREAD

**Issue by coyool** [xyhuangjinfu/MiniDownloader#16]
String resRetr = readCommand();
--
315 | if (!resRetr.startsWith("150")) {
316 | throw new Exception("Download error");

ftp返回代码号对应表 
110 重新启动标记应答。 
120 服务在多久时间内ready。 
125 数据链路埠开启，准备传送。 
150 文件状态正常，开启数据连接端口。 
200 命令执行成功。 
202 命令执行失败。 
211 系统状态或是系统求助响应。 
212 目录的状态。 
213 文件的状态。 
214 求助的讯息。 
215 名称系统类型。 
220 新的联机服务ready。 
221 服务的控制连接埠关闭，可以注销。 
225 数据连结开启，但无传输动作。 
226 关闭数据连接端口，请求的文件操作成功。 
227 进入passive mode。 
230 使用者登入。 
250 请求的文件操作完成。 
257 显示目前的路径名称。 
331 用户名称正确，需要密码。 
332 登入时需要账号信息。 
350 请求的操作需要进一部的命令。 
421 无法提供服务，关闭控制连结。 
425 无法开启数据链路。 
426 关闭联机，终止传输。 
450 请求的操作未执行。 
451 命令终止：有本地的错误。 
452 未执行命令：磁盘空间不足。 
500 格式错误，无法识别命令。 
501 参数语法错误。 
502 命令执行失败。 
503 命令顺序错误。 
504 命令所接的参数不正确。 
530 未登入。 
532 储存文件需要账户登入。 
550 未执行请求的操作。 
551 请求的命令终止，类型未知。 
552 请求的文件终止，储存位溢出。 
553 未执行请求的的命令，名称不正确

**Comment by xyhuangjinfu** [comment]
嗯，是的，所以当响应不是 150 的时候，认为下载出错。不是这样吗？

**Comment by coyool** [comment]
反正我屏蔽了就可以下载了

**Comment by xyhuangjinfu** [comment]
你那边是什么ftp服务器？或者可以发一个测试链接给我看一下吗？如果可以的话，谢了。

**Comment by coyool** [comment]
windows sever 2008 , 自带的IIS建的,

**Comment by xyhuangjinfu** [comment]
抱歉，我这边没有win server 的环境，不好意思，可以给我一个测试用的下载链接吗，谢了。
